[tree]
tree_depth = 30
dense_tree_prefix_depth = 10
tree_gc_threshold = 10000000
cache_file = "./cache_file"

[server]
address = "0.0.0.0:8080"

[network]
identity_manager_address = "0x48483748eb0446A16cAE79141D0688e3F624Cb73"

[relayer]
kind = "tx_sitter"
tx_sitter_url = "http://tx-sitter:3000/1/api/G5CKNF3BTS2hRl60bpdYMNPqXvXsP-QZd2lrtmgctsnllwU9D3Z4D8gOt04M0QNH"
tx_sitter_address = "0x1d7ffed610cc4cdC097ecDc835Ae5FEE93C9e3Da"
tx_sitter_gas_limit = 2000000

[providers]
primary_network_provider = "http://chain:8545"

[app]
provers_urls = '[{"url": "http://semaphore-insertion:3001", "prover_type": "insertion", "batch_size": 10,"timeout_s": 30}, {"url": "http://semaphore-deletion:3001", "prover_type": "deletion", "batch_size": 10,"timeout_s": 30}]'
batch_insertion_timeout = "30s"
batch_deletion_timeout = "1s"

[database]
database = "postgres://postgres:postgres@sequencer-db:5432/sequencer?sslmode=disable"
