name: Update deployment ref number

on:
  push:
    branches:
      - main

jobs:
  update-deployment:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}
          repository: worldcoin/signup-sequencer-deploy
          event-type: update-ref
          client-payload: |
            {
              "ref": "${{ github.sha }}",
              "issuer":  "${{ steps.PR.outputs.pr_url }}"
            }
